# Generated by Django 4.1.5 on 2023-01-27 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytravelapp', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='description',
            new_name='desc1',
        ),
    ]
